version: '3'
services:
  wordpress:
    build: 
      context: '.'
    restart: 'always'
    ports:
      - '${WP_HTTP_PORT}:80'
    environment:
      - 'WORDPRESS_DB_NAME=${DB_NAME}'
      - 'WORDPRESS_DB_USER=${DB_USER}'
      - 'WORDPRESS_DB_PASSWORD=${DB_PASSWORD}'
      - 'WORDPRESS_DB_HOST=mysql'
      - 'WORDPRESS_DEBUG=${WORDPRESS_DEBUG}'
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html'
  